### ISSUE TITLE
Features to be added

### ISSUE THREAD

**Issue by jeremy032312** [jeremy032312/dominion-builder#1]
# TODO

- [ ] Card Library
- [ ] Add Card to Preset
- [ ] Add a new Card to the Library
- [ ] Clear input text upon create a new Preset
- [ ] Randomizer
